receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 4317
      http:
        endpoint: 4318
  prometheus:
    endpoint: 0.0.0.0:9464
exporters:
  otlp/tempo:
    endpoint: http://localhost:4317/v1/traces
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464
  debug:
    verbosity: basic
    endpoint: http://localhost:4318/v1/traces
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug]
